hydra:
  output_subdir: hydra_params
wandb:
  project: FAQEngine
  exp_name: exp_001
path:
  project_path: /content/drive/MyDrive/ML_proj/FAQEngine
  src_dir: colab_exp_src
  client_name: phama_0715
  checkpoint_path: checkpoint
data:
  question_column: Question
  answer_column: Index
  train_valid_split: 0.9
  test_data_size: 500
model:
  pretrained_model: cl-tohoku/bert-base-japanese-whole-word-masking
training:
  num_epochs: 10
  batch_size: 64
  max_token_len: 512
  dropout_rate: 0.1
  learning_rate: 0.0005
  mrr_at_k: 5
